/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as CommandRouteImport } from './routes/command'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as FoundersIdRouteImport } from './routes/founders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersIdRoute = FoundersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FoundersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/command': typeof CommandRoute
  '/decisions': typeof DecisionsRoute
  '/feed': typeof FeedRoute
  '/founders': typeof FoundersRouteWithChildren
  '/triage': typeof TriageRoute
  '/founders/$id': typeof FoundersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/command': typeof CommandRoute
  '/decisions': typeof DecisionsRoute
  '/feed': typeof FeedRoute
  '/founders': typeof FoundersRouteWithChildren
  '/triage': typeof TriageRoute
  '/founders/$id': typeof FoundersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/command': typeof CommandRoute
  '/decisions': typeof DecisionsRoute
  '/feed': typeof FeedRoute
  '/founders': typeof FoundersRouteWithChildren
  '/triage': typeof TriageRoute
  '/founders/$id': typeof FoundersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/command'
    | '/decisions'
    | '/feed'
    | '/founders'
    | '/triage'
    | '/founders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/command'
    | '/decisions'
    | '/feed'
    | '/founders'
    | '/triage'
    | '/founders/$id'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/command'
    | '/decisions'
    | '/feed'
    | '/founders'
    | '/triage'
    | '/founders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  CommandRoute: typeof CommandRoute
  DecisionsRoute: typeof DecisionsRoute
  FeedRoute: typeof FeedRoute
  FoundersRoute: typeof FoundersRouteWithChildren
  TriageRoute: typeof TriageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders/$id': {
      id: '/founders/$id'
      path: '/$id'
      fullPath: '/founders/$id'
      preLoaderRoute: typeof FoundersIdRouteImport
      parentRoute: typeof FoundersRoute
    }
  }
}

interface FoundersRouteChildren {
  FoundersIdRoute: typeof FoundersIdRoute
}

const FoundersRouteChildren: FoundersRouteChildren = {
  FoundersIdRoute: FoundersIdRoute,
}

const FoundersRouteWithChildren = FoundersRoute._addFileChildren(
  FoundersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  CommandRoute: CommandRoute,
  DecisionsRoute: DecisionsRoute,
  FeedRoute: FeedRoute,
  FoundersRoute: FoundersRouteWithChildren,
  TriageRoute: TriageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
